name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Configure and build (${{ matrix.profile }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [ USER, DEVELOPER ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            cmake \
            bison \
            flex \
            zlib1g-dev

      - name: Configure CMake
        run: |
          cmake -S . -B build-${{ matrix.profile }} \
            -DMWRAP_PROFILE=${{ matrix.profile }} \
            -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build build-${{ matrix.profile }} --target mwrap

      - name: Run tests
        run: cmake --build build-${{ matrix.profile }} --target mwrap_tests

  matlab-examples:
    name: Build and test MATLAB examples
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            cmake \
            bison \
            flex \
            zlib1g-dev

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Configure examples with CMake
        run: |
          cmake -S . -B build-matlab \
            -DMWRAP_PROFILE=USER \
            -DMWRAP_BUILD_EXAMPLES=ON \
            -DMWRAP_COMPILE_MEX=ON \
            -DBUILD_TESTING=ON

      - name: Build MATLAB examples
        run: cmake --build build-matlab --target mwrap_examples

  octave-examples:
    name: Build and test Octave examples
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            cmake \
            zlib1g-dev \
            octave \
            octave-dev

      - name: Configure examples with CMake
        run: |
          cmake -S . -B build-octave \
            -DMWRAP_PROFILE=USER \
            -DMWRAP_BUILD_EXAMPLES=ON \
            -DMWRAP_COMPILE_MEX=ON \
            -DMWRAP_MEX_BACKEND=OCTAVE \
            -DBUILD_TESTING=ON

      - name: Build Octave examples
        run: cmake --build build-octave --target mwrap_examples

      - name: Run Octave example tests
        run: ctest --test-dir build-octave --output-on-failure -R '^octave-'
